With MergeData AS (
	SELECT 
        [YearMonth] ,
		[OrgType] ,
		[SubOrgType] ,
		[AccessDesc] ,
		[TerritoryL1] ,
		[TerritoryL1Name] ,
		[TerritoryUserL1] ,
		[TerritoryUserNameL1] ,
		[TerritoryUserL1_userpkid] ,
		[TerritoryL2] ,
		[TerritoryL2Name] ,
		[TerritoryUserL2] ,
		[TerritoryUserNameL2] ,
		[TerritoryUserL2_userpkid] ,
		[TerritoryL3] ,
		[TerritoryL3Name] ,
		[TerritoryUserL3] ,
		[TerritoryUserNameL3] ,
		[TerritoryUserL3_userpkid] ,
		[TerritoryL4] ,
		[TerritoryL4Name] ,
		[TerritoryUserL4] ,
		[TerritoryUserNameL4] ,
		[TerritoryUserL4_userpkid] ,
		[TerritoryL5] ,
		[TerritoryL5Name] ,
		[TerritoryUserL5] ,
		[TerritoryUserNameL5] ,
		[TerritoryUserL5_userpkid] ,
		[UserID] ,
		[UserName] ,
		[userpkid_list]
	FROM [ZLAB_EDW].[dbo].[V_Compliance_GFCScoreCard_KPI_V3]
	UNION ALL
	SELECT 
        [YearMonth] ,
		[OrgType] ,
		[SubOrgType] ,
		[AccessDesc] ,
		[TerritoryL1] ,
		[TerritoryL1Name] ,
		[TerritoryUserL1] ,
		[TerritoryUserNameL1] ,
		[TerritoryUserL1_userpkid] ,
		[TerritoryL2] ,
		[TerritoryL2Name] ,
		[TerritoryUserL2] ,
		[TerritoryUserNameL2] ,
		[TerritoryUserL2_userpkid] ,
		[TerritoryL3] ,
		[TerritoryL3Name] ,
		[TerritoryUserL3] ,
		[TerritoryUserNameL3] ,
		[TerritoryUserL3_userpkid] ,
		[TerritoryL4] ,
		[TerritoryL4Name] ,
		[TerritoryUserL4] ,
		[TerritoryUserNameL4] ,
		[TerritoryUserL4_userpkid] ,
		[TerritoryL5] ,
		[TerritoryL5Name] ,
		[TerritoryUserL5] ,
		[TerritoryUserNameL5] ,
		[TerritoryUserL5_userpkid] ,
		[UserID] ,
		[UserName] ,
		[userpkid_list]

	FROM [ZLAB_EDW].[dbo].[V_Compliance_MeetingQualityScorecard_KPI_V3]
	UNION ALL
	SELECT 
        [YearMonth] ,
		[OrgType] ,
		[SubOrgType] ,
		[AccessDesc] ,
		[TerritoryL1] ,
		[TerritoryL1Name] ,
		[TerritoryUserL1] ,
		[TerritoryUserNameL1] ,
		[TerritoryUserL1_userpkid] ,
		[TerritoryL2] ,
		[TerritoryL2Name] ,
		[TerritoryUserL2] ,
		[TerritoryUserNameL2] ,
		[TerritoryUserL2_userpkid] ,
		[TerritoryL3] ,
		[TerritoryL3Name] ,
		[TerritoryUserL3] ,
		[TerritoryUserNameL3] ,
		[TerritoryUserL3_userpkid] ,
		[TerritoryL4] ,
		[TerritoryL4Name] ,
		[TerritoryUserL4] ,
		[TerritoryUserNameL4] ,
		[TerritoryUserL4_userpkid] ,
		[TerritoryL5] ,
		[TerritoryL5Name] ,
		[TerritoryUserL5] ,
		[TerritoryUserNameL5] ,
		[TerritoryUserL5_userpkid] ,
		[UserID] ,
		[UserName] ,
		[userpkid_list]

	FROM [ZLAB_EDW].[dbo].[V_Compliance_PharmeyesMeetingScoreCard_KPI_V3]
	UNION ALL
	SELECT 
        [YearMonth] ,
		[OrgType] ,
		[SubOrgType] ,
		[AccessDesc] ,
		[TerritoryL1] ,
		[TerritoryL1Name] ,
		[TerritoryUserL1] ,
		[TerritoryUserNameL1] ,
		[TerritoryUserL1_userpkid] ,
		[TerritoryL2] ,
		[TerritoryL2Name] ,
		[TerritoryUserL2] ,
		[TerritoryUserNameL2] ,
		[TerritoryUserL2_userpkid] ,
		[TerritoryL3] ,
		[TerritoryL3Name] ,
		[TerritoryUserL3] ,
		[TerritoryUserNameL3] ,
		[TerritoryUserL3_userpkid] ,
		[TerritoryL4] ,
		[TerritoryL4Name] ,
		[TerritoryUserL4] ,
		[TerritoryUserNameL4] ,
		[TerritoryUserL4_userpkid] ,
		[TerritoryL5] ,
		[TerritoryL5Name] ,
		[TerritoryUserL5] ,
		[TerritoryUserNameL5] ,
		[TerritoryUserL5_userpkid] ,
		[UserID] ,
		[UserName] ,
		[userpkid_list]

	FROM [ZLAB_EDW].[dbo].[V_Compliance_TranscriptScoreCard_KPI_V3]
)



SELECT [YearMonth] ,
		[OrgType] ,
		[SubOrgType] ,
		[AccessDesc] ,
		[TerritoryL1] ,
		[TerritoryL1Name] ,
		[TerritoryUserL1] ,
		[TerritoryUserNameL1] ,
		[TerritoryUserL1_userpkid] ,
		[TerritoryL2] ,
		[TerritoryL2Name] ,
		[TerritoryUserL2] ,
		[TerritoryUserNameL2] ,
		[TerritoryUserL2_userpkid] ,
		[TerritoryL3] ,
		[TerritoryL3Name] ,
		[TerritoryUserL3] ,
		[TerritoryUserNameL3] ,
		[TerritoryUserL3_userpkid] ,
		[TerritoryL4] ,
		[TerritoryL4Name] ,
		[TerritoryUserL4] ,
		[TerritoryUserNameL4] ,
		[TerritoryUserL4_userpkid] ,
		[TerritoryL5] ,
		[TerritoryL5Name] ,
		[TerritoryUserL5] ,
		[TerritoryUserNameL5] ,
		[TerritoryUserL5_userpkid] ,
		[UserID] ,
		[UserName] ,
		value AS AccessUserpkid
FROM 
    (SELECT DISTINCT [YearMonth] ,
		[OrgType] ,
		[SubOrgType] ,
		[AccessDesc] ,
		[TerritoryL1] ,
		[TerritoryL1Name] ,
		[TerritoryUserL1] ,
		[TerritoryUserNameL1] ,
		[TerritoryUserL1_userpkid] ,
		[TerritoryL2] ,
		[TerritoryL2Name] ,
		[TerritoryUserL2] ,
		[TerritoryUserNameL2] ,
		[TerritoryUserL2_userpkid] ,
		[TerritoryL3] ,
		[TerritoryL3Name] ,
		[TerritoryUserL3] ,
		[TerritoryUserNameL3] ,
		[TerritoryUserL3_userpkid] ,
		[TerritoryL4] ,
		[TerritoryL4Name] ,
		[TerritoryUserL4] ,
		[TerritoryUserNameL4] ,
		[TerritoryUserL4_userpkid] ,
		[TerritoryL5] ,
		[TerritoryL5Name] ,
		[TerritoryUserL5] ,
		[TerritoryUserNameL5] ,
		[TerritoryUserL5_userpkid] ,
		[UserID] ,
		[UserName] ,
		CONCAT([TerritoryUserL1_userpkid],
		',',[TerritoryUserL2_userpkid],',',[TerritoryUserL3_userpkid],',',[TerritoryUserL4_userpkid],',',[TerritoryUserL5_userpkid],',',[userpkid_list]) AS [userpkid_list] --,value AS AccessUserpkid
    FROM MergeData	
    WHERE YearMonth
    	BETWEEN '2024-04'
    		AND FORMAT(DATEADD(MONTH,-1,GETDATE()),'yyyy-MM') ) AS A CROSS APPLY 
    (SELECT DISTINCT value
    FROM string_split(A.userpkid_list,',') ) AS SPLIST    