--KPI1 PharmeyesMeetingScoreCard
SELECT [YearMonth]
      ,[OrgType]
      ,[SubOrgType]
      ,[AccessDesc]
      ,[TerritoryL1]
      ,[TerritoryL1Name]
      ,[TerritoryUserL1]
      ,[TerritoryUserNameL1]
      ,[TerritoryUserL1_userpkid]
      ,[TerritoryL2]
      ,[TerritoryL2Name]
      ,[TerritoryUserL2]
      ,[TerritoryUserNameL2]
      ,[TerritoryUserL2_userpkid]
      ,[TerritoryL3]
      ,[TerritoryL3Name]
      ,[TerritoryUserL3]
      ,[TerritoryUserNameL3]
      ,[TerritoryUserL3_userpkid]
      ,[TerritoryL4]
      ,[TerritoryL4Name]
      ,[TerritoryUserL4]
      ,[TerritoryUserNameL4]
      ,[TerritoryUserL4_userpkid]
      ,[TerritoryL5]
      ,[TerritoryL5Name]
      ,[TerritoryUserL5]
      ,[TerritoryUserNameL5]
      ,[TerritoryUserL5_userpkid]
      ,[UserID]
--      ,[MeetingName]
--      ,[IsSelected]
      ,[issues]
      ,[issues_Flg]
      ,[issues_i]
      ,[ActivityNo]
--      ,[CheckVersion]
--      ,[Confirmed]
      ,[UserName]
      ,[userpkid_list]
      ,1 AS KPI 
      ,'PharmeyesMeetingScoreCard' AS KPIDesc
 --     ,'' AS Comments
--	  ,(CASE WHEN SUM([issues_Flg])>1 THEN 1 ELSE SUM([issues_Flg]) END)  AS IssueScore 
--       ,STRING_AGG([issues], ',') WITHIN GROUP (ORDER BY [issues]) AS issueslist
  FROM [ZLAB_EDW].[dbo].[V_Compliance_PharmeyesMeetingScoreCard_KPI_V3]

UNION ALL

--KPI2 MeetingQualityScorecard
SELECT [YearMonth]
      ,[OrgType]
      ,[SubOrgType]
      ,[AccessDesc]
      ,[TerritoryL1]
      ,[TerritoryL1Name]
      ,[TerritoryUserL1]
      ,[TerritoryUserNameL1]
      ,[TerritoryUserL1_userpkid]
      ,[TerritoryL2]
      ,[TerritoryL2Name]
      ,[TerritoryUserL2]
      ,[TerritoryUserNameL2]
      ,[TerritoryUserL2_userpkid]
      ,[TerritoryL3]
      ,[TerritoryL3Name]
      ,[TerritoryUserL3]
      ,[TerritoryUserNameL3]
      ,[TerritoryUserL3_userpkid]
      ,[TerritoryL4]
      ,[TerritoryL4Name]
      ,[TerritoryUserL4]
      ,[TerritoryUserNameL4]
      ,[TerritoryUserL4_userpkid]
      ,[TerritoryL5]
      ,[TerritoryL5Name]
      ,[TerritoryUserL5]
      ,[TerritoryUserNameL5]
      ,[TerritoryUserL5_userpkid]
      ,[UserID]
--      ,[MeetingName]
--      ,[IsSelected]
      ,[issues]
      ,[issues_Flg]
      ,[issues_i]
      ,[ActivityNo]
--      ,[CheckVersion]
--      ,[Confirmed]
      ,[UserName]
      ,[userpkid_list]
      ,2 AS KPI 
      ,'MeetingQualityScorecard' AS KPIDesc
      --,'' AS Comments
	  --,(CASE WHEN SUM([issues_Flg])>1 THEN 1 ELSE SUM([issues_Flg]) END)  AS IssueScore 
       --,STRING_AGG([issues], ',') WITHIN GROUP (ORDER BY [issues]) AS issueslist
  FROM [ZLAB_EDW].[dbo].[V_Compliance_MeetingQualityScorecard_KPI_V3]


UNION ALL
 --KPI3 GFCScoreCard
SELECT [YearMonth]
      ,[OrgType]
      ,[SubOrgType]
      ,[AccessDesc]
      ,[TerritoryL1]
      ,[TerritoryL1Name]
      ,[TerritoryUserL1]
      ,[TerritoryUserNameL1]
      ,[TerritoryUserL1_userpkid]
      ,[TerritoryL2]
      ,[TerritoryL2Name]
      ,[TerritoryUserL2]
      ,[TerritoryUserNameL2]
      ,[TerritoryUserL2_userpkid]
      ,[TerritoryL3]
      ,[TerritoryL3Name]
      ,[TerritoryUserL3]
      ,[TerritoryUserNameL3]
      ,[TerritoryUserL3_userpkid]
      ,[TerritoryL4]
      ,[TerritoryL4Name]
      ,[TerritoryUserL4]
      ,[TerritoryUserNameL4]
      ,[TerritoryUserL4_userpkid]
      ,[TerritoryL5]
      ,[TerritoryL5Name]
      ,[TerritoryUserL5]
      ,[TerritoryUserNameL5]
      ,[TerritoryUserL5_userpkid]
      ,[UserID]
--      ,[MeetingName]
--      ,[IsSelected]
      ,[issues]
      ,[issues_Flg]
      ,[issues_i]
       ,[serialnum] as [ActivityNo]
--      ,[CheckVersion]
--      ,[Confirmed]
      ,[UserName]
      ,[userpkid_list]
      ,3 AS KPI 
      ,'GFCScoreCard' AS KPIDesc
--      ,'' AS Comments
--	  ,(CASE WHEN SUM([issues_Flg])>1 THEN 1 ELSE SUM([issues_Flg]) END)  AS IssueScore 
--       ,STRING_AGG([issues], ',') WITHIN GROUP (ORDER BY [issues]) AS issueslist
  FROM [ZLAB_EDW].[dbo].[V_Compliance_GFCScoreCard_KPI_V3]

UNION ALL

--KPI4 TranscriptScoreCard
SELECT [YearMonth]
      ,[OrgType]
      ,[SubOrgType]
      ,[AccessDesc]
      ,[TerritoryL1]
      ,[TerritoryL1Name]
      ,[TerritoryUserL1]
      ,[TerritoryUserNameL1]
      ,[TerritoryUserL1_userpkid]
      ,[TerritoryL2]
      ,[TerritoryL2Name]
      ,[TerritoryUserL2]
      ,[TerritoryUserNameL2]
      ,[TerritoryUserL2_userpkid]
      ,[TerritoryL3]
      ,[TerritoryL3Name]
      ,[TerritoryUserL3]
      ,[TerritoryUserNameL3]
      ,[TerritoryUserL3_userpkid]
      ,[TerritoryL4]
      ,[TerritoryL4Name]
      ,[TerritoryUserL4]
      ,[TerritoryUserNameL4]
      ,[TerritoryUserL4_userpkid]
      ,[TerritoryL5]
      ,[TerritoryL5Name]
      ,[TerritoryUserL5]
      ,[TerritoryUserNameL5]
      ,[TerritoryUserL5_userpkid]
      ,[UserID]
--      ,[MeetingName]
--      ,[IsSelected]
      ,(CASE WHEN [issues_Flg] = 0 THEN '' ELSE '合规培训' END) [issues]
      ,[issues_Flg]
      ,(CASE WHEN [issues_Flg] = 0 THEN '' ELSE '合规培训' END) [issues_i]
       ,[ActivityNo]
--      ,[CheckVersion]
--      ,[Confirmed]
      ,[UserName]
      ,[userpkid_list]
      ,4 AS KPI 
      ,'TranscriptScoreCard' AS KPIDesc


FROM
(
SELECT DISTINCT
       [YearMonth]
      ,[OrgType]
      ,[SubOrgType]
      ,[AccessDesc]
      ,[TerritoryL1]
      ,[TerritoryL1Name]
      ,[TerritoryUserL1]
      ,[TerritoryUserNameL1]
      ,[TerritoryUserL1_userpkid]
      ,[TerritoryL2]
      ,[TerritoryL2Name]
      ,[TerritoryUserL2]
      ,[TerritoryUserNameL2]
      ,[TerritoryUserL2_userpkid]
      ,[TerritoryL3]
      ,[TerritoryL3Name]
      ,[TerritoryUserL3]
      ,[TerritoryUserNameL3]
      ,[TerritoryUserL3_userpkid]
      ,[TerritoryL4]
      ,[TerritoryL4Name]
      ,[TerritoryUserL4]
      ,[TerritoryUserNameL4]
      ,[TerritoryUserL4_userpkid]
      ,[TerritoryL5]
      ,[TerritoryL5Name]
      ,[TerritoryUserL5]
      ,[TerritoryUserNameL5]
      ,[TerritoryUserL5_userpkid]
      ,[UserID]
      ,bb.TRAININGTITLE as [ActivityNo]
      ,aa.[UserName]
      ,aa.[userpkid_list]
      ,4 AS KPI 
      ,'TranscriptScoreCard' AS KPIDesc
      ,'' AS Comments
	  ,(CASE WHEN ((LEN([CompletedDate]) > 0 AND DATEDIFF(DAY, [CompletedDate], [DueDate]) < 0) 
	  OR (LEN([CompletedDate]) = 0 AND DATEDIFF(DAY, GETDATE(), [DueDate]) < 0) ) AND bb.KPIFLAG = 'Y'
			THEN 1 
			ELSE 0 
		END) AS [issues_Flg]
  FROM [ZLAB_EDW].[dbo].[V_Compliance_TranscriptScoreCard_KPI_V3] AS aa 
  LEFT JOIN [ZLAB_EDW].[dbo].[ODS_Compliance_TrainingList] AS bb
  ON aa.[TrainingTitle] = bb.TRAININGTITLE
  AND aa.[TrainingType] = bb.TRAININGTYPE
 ) AS T
